
const types =  [
    {
        id: 1,
        name: 'accident',
        title: 'Accident',
        icon: '/images/mobility/chantier-de-construction/accident.png',
        active: true,
        type: 'defectuosity',
    },
    {
        id: 2,
        name: 'animalsOnTheRoad',
        title: 'Passage des animaux',
        icon: '/images/mobility/chantier-de-construction/animals-on-the-road.png',
        active: true,
        type: 'defectuosity',
    },
    {
        id: 3,
        name: 'blackIce',
        title: 'Glace noir',
        icon: '/images/mobility/chantier-de-construction/black-ice.png',
        active: true,
        type: 'defectuosity',
    },
    {
        id: 4,
        name: 'brokenDownVehicle',
        title: 'Véhicule en panne',
        icon: '/images/mobility/chantier-de-construction/broken-down-vehicle.png',
        active: true,
        type: 'defectuosity',
    },
    {
        id: 5,
        name: 'laneClosures',
        title: 'Fermetures des voies',
        icon: '/images/mobility/chantier-de-construction/lane-closures.png',
        active: true,
    },

    {
        id: 6,
        name: 'roadworks',
        title: 'Travaux routiers',
        icon: '/images/mobility/chantier-de-construction/road-works.png',
        active: true,
    },

    {
        id: 7,
        name: 'repairWork',
        title: 'Réparation du routes',
        icon: '/images/mobility/chantier-de-construction/repair-work.png',
        active: true,
    },
    {
        id: 8,
        name: 'roadClosed',
        title: 'Route barrées',
        icon: '/images/mobility/chantier-de-construction/road-closed.png',
        active: true,
    },
    {
        id: 9,
        name: 'roadsideWork',
        title: 'Travaux en bordure de route',
        icon: '/images/mobility/chantier-de-construction/road-side-work.png',
        active: true,
    },
    {
        id: 10,
        name: 'slipperyRoad',
        title: 'Route glissantes',
        icon: '/images/mobility/chantier-de-construction/slippery-road.png',
        active: true,
        type: 'defectuosity',
    },
    {
        id: 11,
        name: 'obstructionOnTheRoad',
        title: 'Obstruction sur la route',
        icon: '/images/mobility/chantier-de-construction/obstruction-road.png',
        active: true,
        type: 'defectuosity',
    },
    {
        id: 12,
        name: 'abandonedVehicle',
        title: 'Route glissantes',
        icon: '/images/mobility/chantier-de-construction/abandoned-vehicle.png',
        active: true,
        type: 'defectuosity',
    },
    {
        id: 13,
        name: 'snowOnTheRoad',
        title: 'Neige sur la route',
        icon: '/images/mobility/chantier-de-construction/black-ice.png',
        active: true,
        type: 'defectuosity',
    },
    /*   {
        id: 14,
        name: 'snowOnTheRoad',
        title: 'Route glissantes',
        icon: '/images/mobility/chantier-de-construction/cone.png',
        active: true,
    }, */
    {
        id: 15,
        name: 'narrowLanes',
        title: 'ruelles étroites',
        icon: '/images/mobility/chantier-de-construction/narrow-lanes.png',
        active: true,
    },
    {
        id: 16,
        name: 'slowTraffic',
        title: 'Trafic lent',
        icon: '/images/mobility/chantier-de-construction/slow-trafic.png',
        active: true,
    },
    {
        id: 17,
        name: 'vehicleStuck',
        title: 'Véhicule coincé',
        icon: '/images/mobility/chantier-de-construction/vehicle-stuck.png',
        active: true,
        type: 'defectuosity',
    },
    {
        id: 18,
        name: 'maintenanceWork',
        title: "travail d'entretien",
        icon: '/images/mobility/chantier-de-construction/maintenance-work.png',
        active: true,
    },
    /*  {
        id: 19,
        name: 'maintenanceWork',
        title: 'ruelles étroites',
        icon: '/images/mobility/chantier-de-construction/narrow-lanes.png',
        active: true,
    }, */
    {
        id: 20,
        name: 'grassCuttingWork',
        title: "Travail de coupe d'herbe",
        icon: '/images/mobility/chantier-de-construction/grass-cutting-work.png',
        active: true,
    },
    {
        id: 21,
        name: 'singleAlternateLineTraffic',
        title: 'Trafic de ligne alternative simple',
        icon: '/images/mobility/chantier-de-construction/signal-altrenate-line-traffic.png',
        active: true,
    },
    /*   {
        id: 22,
        name: 'singleAlternateLineTraffic',
        title: 'ruelles étroites',
        icon: '/images/mobility/chantier-de-construction/narrow-lanes.png',
        active: true,
    }, */
    {
        id: 23,
        name: 'resurfacingWork',
        title: 'Travaux de resurfaçage',
        icon: '/images/mobility/chantier-de-construction/resurfacing-work.png',
        active: true,
    },
    {
        id: 24,
        name: 'doNotUseExit',
        title: 'ne pas utiliser Quitter',
        icon: '/images/mobility/chantier-de-construction/do-not-use-uxit.png',
        active: true,
    },
    {
        id: 25,
        name: 'other',
        title: 'Autres',
        icon: '/images/mobility/chantier-de-construction/other.png',
        active: true,
    },
];

export default types;
