export const relativeWorkConnectionElectricity = [
    {
        key: 'Déplacer le branchement',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'https://extranet.ores.be/fr/work-demands/existing-connection',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/nouveau-raccordement-gaz',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'Elektriciteitsaansluiting ondergronds brengen',
                    cost: '1.350,98',
                    link: 'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen'
                },
                {
                    provider: 'FLUVIUS',
                    id: 2,
                    type: 'Verplaatsen aansluiting en verplaatsen elektriciteitsmeter zonder verdere aanpassingen',
                    cost: '1231,27',
                    link: 'https://mijnportaal.eandis.be/nl/Login/NewWorkRequest/?fluviusId=7c2a13ee-548c-4a46-8c14-6a9b5f025dec'
                },
                {
                    provider: 'FLUVIUS',
                    id: 3,
                    type: 'Ondergronds brengen aansluiting en verplaatsing elektriciteitsmeter',
                    cost: '1620,09',
                    link: 'https://mijnportaal.eandis.be/nl/Login/NewWorkRequest/?fluviusId=7c2a13ee-548c-4a46-8c14-6a9b5f025dec'
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: 'Raccordements avec cabine sur réseau MPB (moyenne pression: >160m3/h)',
                    titles: [
                        'Débit horaire maximum (m³/h)',
                        'Type compteur',
                        'Pression maximale de (bar)',
                        'Conduite type (max. 25 m)',
                        'Prix',
                        'Détente 1 ligne Prix',
                    ],
                    cost: [
                        {
                            id: 1,
                            hourlyFlow: '250',
                            counterType: 'G160',
                            maxPressure: '4,9',
                            typicalConduct: 'PE63',
                            price: '2.959',
                            relaxOneLine: '12.129',
                        },
                        {
                            id: 2,
                            hourlyFlow: '400',
                            counterType: 'G250',
                            maxPressure: '4,9',
                            typicalConduct: 'PE63',
                            price: '2.959',
                            relaxOneLine: '15.492',
                        },
                        {
                            id: 3,
                            hourlyFlow: '650',
                            counterType: 'G400',
                            maxPressure: '4,9',
                            typicalConduct: 'PE110',
                            price: '4.719',
                            relaxOneLine: '18.854',
                        },
                        {
                            id: 4,
                            hourlyFlow: '1.000',
                            counterType: 'G650',
                            maxPressure: '4,9',
                            typicalConduct: 'PE110',
                            price: '4.719',
                            relaxOneLine: '24.326',
                        },
                        {
                            id: 5,
                            hourlyFlow: '1.600',
                            counterType: 'G1000',
                            maxPressure: '4,9',
                            typicalConduct: 'PE160',
                            price: '5.112',
                            relaxOneLine: 'pas disponible',
                        },
                    ],
                },
                {
                    provider: 'ORES',
                    id: 2,
                    type: 'Raccordement Gaz sur réseau de distribution basse pression (BP) ou sur réseau de distribution moyenne pression (MP ≤5 bar) avec pression de sortie 21/25/98 mbar, et avec un débit maximum de 160 m³/h',
                    titles: [
                        'Débit horaire maximum (m³/h)',
                        'Type compteur',
                        'Coffret/mini-cabine',
                        'Conduite',
                        'BP 21/25/98 mbar',
                        'MP 4,9 bar',
                        'BP 21/25/98 mbar',
                        'MP 4,9 bar',
                        'Coffrets',
                    ],
                    cost: [
                        {
                            id: 1,
                            hourlyFlow: '6-10',
                            counterType: 'G4 - G6',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'PE32',
                            BP212598mbar1: '634',
                            MP49bar1: '634',
                            BP212598mbar2: '262',
                            MP49bar2: '262',
                            box: '285',
                        },
                        {
                            id: 2,
                            hourlyFlow: '16',
                            counterType: 'G10',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 ou PE32 - MP: PE32',
                            BP212598mbar1: '634',
                            MP49bar1: '634',
                            BP212598mbar2: '324',
                            MP49bar2: '324',
                            box: '742',
                        },
                        {
                            id: 3,
                            hourlyFlow: '25',
                            counterType: 'G16',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 ou PE32 - MP: PE32',
                            BP212598mbar1: '634',
                            MP49bar1: '634',
                            BP212598mbar2: '324',
                            MP49bar2: '324',
                            box: '742',
                        },
                        {
                            id: 4,
                            hourlyFlow: '40',
                            counterType: 'G25',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 - MP: PE32',
                            BP212598mbar1: '1.267',
                            MP49bar1: '1.267',
                            BP212598mbar2: '1.464',
                            MP49bar2: '1.464',
                            box: '746',
                        },
                        {
                            id: 5,
                            hourlyFlow: '65',
                            counterType: 'G40',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE63(****) - MP: PE32',
                            BP212598mbar1: '1.267',
                            MP49bar1: '1.267',
                            BP212598mbar2: '3.404',
                            MP49bar2: '3.758',
                            box: '1.815',
                        },
                        {
                            id: 6,
                            hourlyFlow: '100',
                            counterType: 'G65',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE110 ou PE63 - MP: PE32',
                            BP212598mbar1: '1.690',
                            MP49bar1: '1.690',
                            BP212598mbar2: '5.017',
                            MP49bar2: '5.538',
                            box: '2.560',
                        },
                        {
                            id: 7,
                            hourlyFlow: '160',
                            counterType: 'G100',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE110 ou PE63 - MP: PE32',
                            BP212598mbar1: '2.030',
                            MP49bar1: '2.030',
                            BP212598mbar2: '6.993',
                            MP49bar2: '6.993',
                            box: '2.560',
                        },
                    ],
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "Placement d'un branchement gaz avec un débit Q <= 40 m³/h en cas de pose d'un compteur G4/G6 (Promo)(pose de 1 compteur type G4/G6 compris)",
                    cost: '474,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "Placement d'un branchement gaz avec un débit Q <= 40m³/h en cas de placement de plusieurs compteurs(compteurs non-compris)",
                    cost: '1126,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "Placement d'un branchement gaz Q > 40 m³/h (compteurs non-compris)",
                    cost: '1880,00',
                },
            ],
        },
    },
    {
        key: 'Renforcer le branchement',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'https://extranet.ores.be/fr/work-demands/existing-connection',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/nouveau-raccordement-gaz',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'Verminderen vermogen elektriciteit',
                    cost: '269,12',
                },
                {
                    provider: 'FLUVIUS',
                    id: 2,
                    type: 'Verzwaren vermogen op tweefasige elektriciteitsaansluiting tot 9,2 kVA',
                    cost: '269,12',
                },
                {
                    provider: 'FLUVIUS',
                    id: 3,
                    type: 'Verzwaren vermogen op tweefasige elektriciteitsaansluiting van 9,2 kVA naar 11,5 kVA ',
                    cost: '310,90',
                },
                {
                    provider: 'FLUVIUS',
                    id: 4,
                    type: ' Verzwaren vermogen elektriciteit van 15,9 kVA naar 25VA op 230V ',
                    cost: '522,59',
                },
                {
                    provider: 'FLUVIUS',
                    id: 5,
                    type: 'Verzwaren vermogen elektriciteit van 17,3 kVA naar 22,2 kVA op 400V',
                    cost: '405,60',
                },
                {
                    provider: 'FLUVIUS',
                    id: 6,
                    type: 'Verzwaren vermogen bestaande elektriciteitsinstallatie van 22,2 kVA naar 55,4 kVA (400V)',
                    cost: '1442,99',
                },
                {
                    provider: 'FLUVIUS',
                    id: 7,
                    type: ' Verzwaren vermogen bestaande elektriciteitsinstallatie van 69,2 kVA naar 110,7 kVA (400V)',
                    cost: '1923,28',
                },
                {
                    provider: 'FLUVIUS',
                    id: 8,
                    type: ' 400V op vraag met vermogenstijging van 12,7 kVA naar 22,2 kVA Meting NOK, aansluitkabel OK, ,Net 230V en 400V zijn reeds aanwezig,',
                    cost: '1499,00',
                },
                {
                    provider: 'FLUVIUS',
                    id: 9,
                    type: '400V op vraag met vermogenstijging van 12,7 kVA naar 22,2 kVA Meting NOK, aansluitkabel OK, Net 230V, ombouw net, aansluiting aan te passen',
                    cost: '1670,43',
                },
                {
                    provider: 'FLUVIUS',
                    id: 10,
                    type: '400V op vraag zonder vermogensstijging (vb 19,9 kVA op 230V naar 17,3 kVA op 400V) Aansluitkabel en aansluiting OK, nieuw net bij te plaatsen',
                    cost: '1772,75',
                },
                {
                    provider: 'FLUVIUS',
                    id: 11,
                    type: ' E 400V op vraag met vermogenstijging van 19,9 kVA naar 34,6 kVA Aansluitkabel te verzwaren, aan te sluiten op om te bouwen netkabel ',
                    cost: '2064,38',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: 'Raccordements avec cabine sur réseau MPB (moyenne pression: >160m3/h)',
                    titles: [
                        'Débit horaire maximum (m³/h)',
                        'Type compteur',
                        'Pression maximale de (bar)',
                        'Conduite type (max. 25 m)',
                        'Prix',
                        'Détente 1 ligne Prix',
                    ],
                    cost: [
                        {
                            id: 1,
                            hourlyFlow: '250',
                            counterType: 'G160',
                            maxPressure: '4,9',
                            typicalConduct: 'PE63',
                            price: '2.959',
                            relaxOneLine: '12.129',
                        },
                        {
                            id: 2,
                            hourlyFlow: '400',
                            counterType: 'G250',
                            maxPressure: '4,9',
                            typicalConduct: 'PE63',
                            price: '2.959',
                            relaxOneLine: '15.492',
                        },
                        {
                            id: 3,
                            hourlyFlow: '650',
                            counterType: 'G400',
                            maxPressure: '4,9',
                            typicalConduct: 'PE110',
                            price: '4.719',
                            relaxOneLine: '18.854',
                        },
                        {
                            id: 4,
                            hourlyFlow: '1.000',
                            counterType: 'G650',
                            maxPressure: '4,9',
                            typicalConduct: 'PE110',
                            price: '4.719',
                            relaxOneLine: '24.326',
                        },
                        {
                            id: 5,
                            hourlyFlow: '1.600',
                            counterType: 'G1000',
                            maxPressure: '4,9',
                            typicalConduct: 'PE160',
                            price: '5.112',
                            relaxOneLine: 'pas disponible',
                        },
                    ],
                },
                {
                    provider: 'ORES',
                    id: 2,
                    type: 'Raccordement Gaz sur réseau de distribution basse pression (BP) ou sur réseau de distribution moyenne pression (MP ≤5 bar) avec pression de sortie 21/25/98 mbar, et avec un débit maximum de 160 m³/h',
                    titles: [
                        'Débit horaire maximum (m³/h)',
                        'Type compteur',
                        'Coffret/mini-cabine',
                        'Conduite',
                        'BP 21/25/98 mbar',
                        'MP 4,9 bar',
                        'BP 21/25/98 mbar',
                        'MP 4,9 bar',
                        'Coffrets',
                    ],
                    cost: [
                        {
                            id: 1,
                            hourlyFlow: '6-10',
                            counterType: 'G4 - G6',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'PE32',
                            BP212598mbar1: '634',
                            MP49bar1: '634',
                            BP212598mbar2: '262',
                            MP49bar2: '262',
                            box: '285',
                        },
                        {
                            id: 2,
                            hourlyFlow: '16',
                            counterType: 'G10',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 ou PE32 - MP: PE32',
                            BP212598mbar1: '634',
                            MP49bar1: '634',
                            BP212598mbar2: '324',
                            MP49bar2: '324',
                            box: '742',
                        },
                        {
                            id: 3,
                            hourlyFlow: '25',
                            counterType: 'G16',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 ou PE32 - MP: PE32',
                            BP212598mbar1: '634',
                            MP49bar1: '634',
                            BP212598mbar2: '324',
                            MP49bar2: '324',
                            box: '742',
                        },
                        {
                            id: 4,
                            hourlyFlow: '40',
                            counterType: 'G25',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 - MP: PE32',
                            BP212598mbar1: '1.267',
                            MP49bar1: '1.267',
                            BP212598mbar2: '1.464',
                            MP49bar2: '1.464',
                            box: '746',
                        },
                        {
                            id: 5,
                            hourlyFlow: '65',
                            counterType: 'G40',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE63(****) - MP: PE32',
                            BP212598mbar1: '1.267',
                            MP49bar1: '1.267',
                            BP212598mbar2: '3.404',
                            MP49bar2: '3.758',
                            box: '1.815',
                        },
                        {
                            id: 6,
                            hourlyFlow: '100',
                            counterType: 'G65',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE110 ou PE63 - MP: PE32',
                            BP212598mbar1: '1.690',
                            MP49bar1: '1.690',
                            BP212598mbar2: '5.017',
                            MP49bar2: '5.538',
                            box: '2.560',
                        },
                        {
                            id: 7,
                            hourlyFlow: '160',
                            counterType: 'G100',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE110 ou PE63 - MP: PE32',
                            BP212598mbar1: '2.030',
                            MP49bar1: '2.030',
                            BP212598mbar2: '6.993',
                            MP49bar2: '6.993',
                            box: '2.560',
                        },
                    ],
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "Placement d'un branchement gaz avec un débit Q <= 40 m³/h en cas de pose d'un compteur G4/G6 (Promo)(pose de 1 compteur type G4/G6 compris)",
                    cost: '474,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "Placement d'un branchement gaz avec un débit Q <= 40m³/h en cas de placement de plusieurs compteurs(compteurs non-compris)",
                    cost: '1126,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "Placement d'un branchement gaz Q > 40 m³/h (compteurs non-compris)",
                    cost: '1880,00',
                },
            ],
        },
    },
    {
        key: 'Allonger le branchement',
        linkRedirection: {
            FLUVIUS:
                'https://mijnportaal.eandis.be/nl/Login/NewWorkRequest/?fluviusId=7c2a13ee-548c-4a46-8c14-6a9b5f025dec',
            ORES: 'https://extranet.ores.be/fr/work-demands/existing-connection',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/nouveau-raccordement-gaz',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'Verplaatsen aansluiting en verplaatsen elektriciteitsmeter zonder verdere aanpassingen',
                    cost: '1231,27',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: 'Raccordements avec cabine sur réseau MPB (moyenne pression: >160m3/h)',
                    titles: [
                        'Débit horaire maximum (m³/h)',
                        'Type compteur',
                        'Pression maximale de (bar)',
                        'Conduite type (max. 25 m)',
                        'Prix',
                        'Détente 1 ligne Prix',
                    ],
                    cost: [
                        {
                            id: 1,
                            hourlyFlow: '250',
                            counterType: 'G160',
                            maxPressure: '4,9',
                            typicalConduct: 'PE63',
                            price: 'SUR DEVIS',
                            relaxOneLine: 'SUR DEVIS',
                        },
                        {
                            id: 2,
                            hourlyFlow: '400',
                            counterType: 'G250',
                            maxPressure: '4,9',
                            typicalConduct: 'PE63',
                            price: 'SUR DEVIS',
                            relaxOneLine: 'SUR DEVIS',
                        },
                        {
                            id: 3,
                            hourlyFlow: '650',
                            counterType: 'G400',
                            maxPressure: '4,9',
                            typicalConduct: 'PE110',
                            price: 'SUR DEVIS',
                            relaxOneLine: 'SUR DEVIS',
                        },
                        {
                            id: 4,
                            hourlyFlow: '1.000',
                            counterType: 'G650',
                            maxPressure: '4,9',
                            typicalConduct: 'PE110',
                            price: 'SUR DEVIS',
                            relaxOneLine: 'SUR DEVIS',
                        },
                        {
                            id: 5,
                            hourlyFlow: '1.600',
                            counterType: 'G1000',
                            maxPressure: '4,9',
                            typicalConduct: 'PE160',
                            price: 'SUR DEVIS',
                            relaxOneLine: 'SUR DEVIS',
                        },
                    ],
                },
                {
                    provider: 'ORES',
                    id: 2,
                    type: 'Raccordement Gaz sur réseau de distribution basse pression (BP) ou sur réseau de distribution moyenne pression (MP ≤5 bar) avec pression de sortie 21/25/98 mbar, et avec un débit maximum de 160 m³/h',
                    titles: [
                        'Débit horaire maximum (m³/h)',
                        'Type compteur',
                        'Coffret/mini-cabine',
                        'Conduite',
                        'BP 21/25/98 mbar',
                        'MP 4,9 bar',
                        'BP 21/25/98 mbar',
                        'MP 4,9 bar',
                        'Coffrets',
                    ],
                    cost: [
                        {
                            id: 1,
                            hourlyFlow: '6-10',
                            counterType: 'G4 - G6',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'PE32',
                            BP212598mbar1: 'SUR DEVIS',
                            MP49bar1: 'SUR DEVIS',
                            BP212598mbar2: 'SUR DEVIS',
                            MP49bar2: 'SUR DEVIS',
                            box: 'SUR DEVIS',
                        },
                        {
                            id: 2,
                            hourlyFlow: '16',
                            counterType: 'G10',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 ou PE32 - MP: PE32',
                            BP212598mbar1: 'SUR DEVIS',
                            MP49bar1: 'SUR DEVIS',
                            BP212598mbar2: 'SUR DEVIS',
                            MP49bar2: 'SUR DEVIS',
                            box: 'SUR DEVIS',
                        },
                        {
                            id: 3,
                            hourlyFlow: '25',
                            counterType: 'G16',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 ou PE32 - MP: PE32',
                            BP212598mbar1: 'SUR DEVIS',
                            MP49bar1: 'SUR DEVIS',
                            BP212598mbar2: 'SUR DEVIS',
                            MP49bar2: 'SUR DEVIS',
                            box: 'SUR DEVIS',
                        },
                        {
                            id: 4,
                            hourlyFlow: '40',
                            counterType: 'G25',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 - MP: PE32',
                            BP212598mbar1: 'SUR DEVIS',
                            MP49bar1: 'SUR DEVIS',
                            BP212598mbar2: 'SUR DEVIS',
                            MP49bar2: 'SUR DEVIS',
                            box: 'SUR DEVIS',
                        },
                        {
                            id: 5,
                            hourlyFlow: '65',
                            counterType: 'G40',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE63(****) - MP: PE32',
                            BP212598mbar1: 'SUR DEVIS',
                            MP49bar1: 'SUR DEVIS',
                            BP212598mbar2: 'SUR DEVIS',
                            MP49bar2: 'SUR DEVIS',
                            box: 'SUR DEVIS',
                        },
                        {
                            id: 6,
                            hourlyFlow: '100',
                            counterType: 'G65',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE110 ou PE63 - MP: PE32',
                            BP212598mbar1: 'SUR DEVIS',
                            MP49bar1: 'SUR DEVIS',
                            BP212598mbar2: 'SUR DEVIS',
                            MP49bar2: 'SUR DEVIS',
                            box: 'SUR DEVIS',
                        },
                        {
                            id: 7,
                            hourlyFlow: '160',
                            counterType: 'G100',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE110 ou PE63 - MP: PE32',
                            BP212598mbar1: 'SUR DEVIS',
                            MP49bar1: 'SUR DEVIS',
                            BP212598mbar2: 'SUR DEVIS',
                            MP49bar2: 'SUR DEVIS',
                            box: 'SUR DEVIS',
                        },
                    ],
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "Placement d'un branchement gaz avec un débit Q <= 40 m³/h en cas de pose d'un compteur G4/G6 (Promo)(pose de 1 compteur type G4/G6 compris)",
                    cost: '474,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "Placement d'un branchement gaz avec un débit Q <= 40m³/h en cas de placement de plusieurs compteurs(compteurs non-compris)",
                    cost: '1126,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "Placement d'un branchement gaz Q > 40 m³/h (compteurs non-compris)",
                    cost: '1880,00',
                },
            ],
        },
    },

    {
        key: 'Enlever le branchement',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'https://extranet.ores.be/fr/work-demands/existing-connection',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/enlevement-raccordement-gaz',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'Sloop ondergrondse aansluiting met 1 elektriciteitsmeter',
                    cost: '712,19',
                },
                {
                    provider: 'FLUVIUS',
                    id: 2,
                    type: 'Sloop ondergrondse aansluiting met 2 elektriciteitsmeters',
                    cost: '762,51',
                },
                {
                    provider: 'FLUVIUS',
                    id: 3,
                    type: 'Sloop bovengrondse aansluiting met 1 elektriciteitsmeter',
                    cost: '285,37',
                },
                {
                    provider: 'FLUVIUS',
                    id: 4,
                    type: 'Sloop bovengrondse aansluiting met 2 elektriciteitsmeters',
                    cost: '335,68',
                },
                {
                    provider: 'FLUVIUS',
                    id: 5,
                    type: 'Sloop tijdelijke werfaansluiting aansluiting met 1 elektriciteitsmeter',
                    cost: '285,37',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: 'Réseau de distribution alimenté par une cabine sur réseau gaz naturel MPavec un débit supérieur à 160 m³/h',
                    subType: [
                        {
                            id: 1,
                            name: "Radiation d'un branchement jusqu'à PE63 ou Ac50 (enlèvement ou déplacement du dernier compteur non compris) ",
                            cost: '848',
                        },
                        {
                            id: 2,
                            name: "Radiation d'un branchement jusqu'à PE110 ou Ac100 (enlèvement ou déplacement du dernier compteur compris",
                            cost: '3273 ',
                        },
                        {
                            id: 3,
                            name: "Radiation d'un branchement jusqu'à PE160 ou Ac150 (enlèvement ou déplacement du dernier compteur compris)",
                            cost: '3680',
                        },
                    ],
                },
                {
                    provider: 'ORES',
                    id: 2,
                    type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h',
                    cost: '848',
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "[Basse pression] Placement d'un branchement gaz avec un débit Q <= 40 m³/h en cas de pose d'un compteur G4/G6 (Promo)(pose de 1 compteur type G4/G6 compris)",
                    cost: '474,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "[Basse pression] Placement d'un branchement gaz avec un débit Q <= 40m³/h en cas de placement de plusieurs compteurs(compteurs non-compris)",
                    cost: '1126,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "[Basse pression] Placement d'un branchement gaz Q > 40 m³/h (compteurs non-compris)",
                    cost: '1880,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 4,
                    type: '[Moyenne pression] Coupure branchement MP avec un débit <= 160 m³/h',
                    cost: '2686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 5,
                    type: '[Moyenne pression] Coupure branchement MP avec un débit > 160 m³/h',
                    cost: '4028,00',
                },
            ],
        },
    },
];

export const relativeWorkCounterElectricity = [
    {
        key: 'Placer un compteur additionnel',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'https://extranet.ores.be/fr/work-demands/existing-connection',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/placement-nouveau-compteur-gaz',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: "Meetinrichting LD <=10 m³n/h (bij)plaatsen normaal tarief",
                    cost: '412,44',
                },
                {
                    provider: 'FLUVIUS',
                    id: 2,
                    type: "Meetinrichting LD <=10 m³n/h (bij)plaatsen verlaagd tarief ",
                    cost: '250,00',
                },
                {
                    provider: 'FLUVIUS',
                    id: 3,
                    type: "Meetinrichting LD <=10 m³n/h (bij)plaatsen verlaagd tariefMeetinrichting LD >10 m³n/h (bij)plaatsen",
                    cost: '979,74',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 2,
                    type: 'Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h',
                    titles: [
                        'Débit horaire maximum (m³/h)',
                        'Type compteur',
                        'Coffret/mini-cabine',
                        'Conduite',
                        'BP 21/25/98 mbar',
                        'MP 4,9 bar',
                        'BP 21/25/98 mbar',
                        'MP 4,9 bar',
                        'Coffrets',
                    ],
                    cost: [
                        {
                            id: 1,
                            hourlyFlow: '6-10',
                            counterType: 'G4 - G6',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'PE32',
                            BP212598mbar1: '634',
                            MP49bar1: '634',
                            BP212598mbar2: '262',
                            MP49bar2: '262',
                            box: '285',
                        },
                        {
                            id: 2,
                            hourlyFlow: '16',
                            counterType: 'G10',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 ou PE32 - MP: PE32',
                            BP212598mbar1: '634',
                            MP49bar1: '634',
                            BP212598mbar2: '324',
                            MP49bar2: '324',
                            box: '742',
                        },
                        {
                            id: 3,
                            hourlyFlow: '25',
                            counterType: 'G16',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 ou PE32 - MP: PE32',
                            BP212598mbar1: '634',
                            MP49bar1: '634',
                            BP212598mbar2: '324',
                            MP49bar2: '324',
                            box: '742',
                        },
                        {
                            id: 4,
                            hourlyFlow: '40',
                            counterType: 'G25',
                            boxOrMiniCabin: 'coffret',
                            conduct: 'BP: PE63 - MP: PE32',
                            BP212598mbar1: '1.267',
                            MP49bar1: '1.267',
                            BP212598mbar2: '1.464',
                            MP49bar2: '1.464',
                            box: '746',
                        },
                        {
                            id: 5,
                            hourlyFlow: '65',
                            counterType: 'G40',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE63(****) - MP: PE32',
                            BP212598mbar1: '1.267',
                            MP49bar1: '1.267',
                            BP212598mbar2: '3.404',
                            MP49bar2: '3.758',
                            box: '1.815',
                        },
                        {
                            id: 6,
                            hourlyFlow: '100',
                            counterType: 'G65',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE110 ou PE63 - MP: PE32',
                            BP212598mbar1: '1.690',
                            MP49bar1: '1.690',
                            BP212598mbar2: '5.017',
                            MP49bar2: '5.538',
                            box: '2.560',
                        },
                        {
                            id: 7,
                            hourlyFlow: '160',
                            counterType: 'G100',
                            boxOrMiniCabin: 'coffret/mini-cabine',
                            conduct: 'BP: PE110 ou PE63 - MP: PE32',
                            BP212598mbar1: '2.030',
                            MP49bar1: '2.030',
                            BP212598mbar2: '6.993',
                            MP49bar2: '6.993',
                            box: '2.560',
                        },
                    ],
                },
                {
                    provider: 'ORES',
                    id: 3,
                    type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h',
                    cost: {
                        columnA: {
                            titles: [
                                'Débit horaire maximum (m³/h)',
                                'Type compteur',
                                'Coffret/mini-cabine',
                                'Conduite',
                            ],
                            contents: [
                                {
                                    id: 1,
                                    maxHourlyFlow: '6-10',
                                    counterType: 'G4 - G6',
                                    box: 'coffret',
                                    conduct: 'PE32',
                                },
                                {
                                    id: 2,
                                    maxHourlyFlow: '16',
                                    counterType: 'G10',
                                    box: 'coffret',
                                    conduct: 'BP: PE63 ou PE32 - MP: PE32',
                                },
                                {
                                    id: 3,
                                    maxHourlyFlow: '25',
                                    counterType: 'G16',
                                    box: 'coffret',
                                    conduct: 'BP: PE63 ou PE32 - MP: PE32',
                                },
                                {
                                    id: 4,
                                    maxHourlyFlow: '40',
                                    counterType: 'G25',
                                    box: 'coffret',
                                    conduct: 'BP: PE63 - MP: PE32',
                                },
                                {
                                    id: 5,
                                    maxHourlyFlow: '65',
                                    counterType: 'G40',
                                    box: 'coffret/mini-cabine',
                                    conduct: 'BP: PE63(****) - MP: PE32',
                                },
                                {
                                    id: 6,
                                    maxHourlyFlow: '100',
                                    counterType: 'G65',
                                    box: 'coffret/mini-cabine',
                                    conduct: 'BP: PE110 ou PE63 - MP: PE32',
                                },
                                {
                                    id: 7,
                                    maxHourlyFlow: '160',
                                    counterType: 'G100',
                                    box: 'coffret/mini-cabine',
                                    conduct: 'BP: PE110 ou PE63 - MP: PE32',
                                },
                            ],
                        },
                        columnB: {
                            titles: [
                                'BP 21/25/98 mbar',
                                'MP 4,9 bar',
                                'Coffret',
                            ],
                            contents: [
                                {
                                    id: 1,
                                    BP212598mbar: '262',
                                    MP49bar: '262',
                                    box: '285',
                                },
                                {
                                    id: 2,
                                    BP212598mbar: '324',
                                    MP49bar: '324',
                                    box: '742',
                                },
                                {
                                    id: 3,
                                    BP212598mbar: '324',
                                    MP49bar: '324',
                                    box: '742',
                                },
                                {
                                    id: 4,
                                    BP212598mbar: '1.464',
                                    MP49bar: '1.464',
                                    box: '746',
                                },
                                {
                                    id: 5,
                                    BP212598mbar: '3.404',
                                    MP49bar: '3.758',
                                    box: '1.815',
                                },
                                {
                                    id: 6,
                                    BP212598mbar: '5.017',
                                    MP49bar: '5.538',
                                    box: '2.560',
                                },
                                {
                                    id: 7,
                                    BP212598mbar: '6.993',
                                    MP49bar: '6.993',
                                    box: '2.560',
                                },
                            ],
                        },
                    },
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "Placement d'un compteur gaz de type G4/G6",
                    cost: '147,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "Placement d'un compteur gaz G10/G16",
                    cost: '383,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "Placement d'un compteur gaz G25",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 4,
                    type: "Placement d'un compteur gaz G40",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 5,
                    type: "Placement d'un compteur gaz G65",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 6,
                    type: "Placement d'un compteur gaz G100",
                    cost: '447,00',
                },
            ],
        },
    },
    {
        key: 'Placement d’un boîtier impuls basse pression',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'https://extranet.ores.be/fr/work-demands/existing-connection',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/nouveau-raccordement-gaz',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'Ter beschikking stellen impulsen gasmeter vanaf G10 (achteraf aangevraagd). Eventuele noodzakelijke vervanging gasmeter niet inbegrepen',
                    cost: '535,95',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: 'Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h',
                    subType: [
                        {
                            id: 1,
                            name: "Mise à disposition d'impulsions compteur gaz (demandé a posteriori) (l'éventuel et nécessaire remplacement du compteur gaz non inclus)",
                            cost: '855',
                        },
                        {
                            id: 2,
                            name: "Mise à disposition d'impulsions compteur gaz : avec changement ou adaptation du compteur G160",
                            cost: '3273 ',
                        },
                        {
                            id: 3,
                            name: "avec changement ou adaptation du compteur G250",
                            cost: '3106',
                        },
                        {
                            id: 4,
                            name: "avec changement ou adaptation du compteur G400",
                            cost: '6176',
                        },
                        {
                            id: 5,
                            name: "avec changement ou adaptation du compteur G650",
                            cost: '3611',
                        },
                        {
                            id: 6,
                            name: "avec changement ou adaptation du compteur G1000 ",
                            cost: '4899',
                        },
                        {
                            id: 7,
                            name: "avec changement ou adaptation du compteur ≥ G1600",
                            cost: 'Sur devis',
                        },
                    ],
                },
                {
                    provider: 'ORES',
                    id: 2,
                    type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h',
                    cost: '855',
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "[Basse pression] Placement d'un compteur gaz de type G4/G6",
                    cost: '147,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "[Basse pression] Placement d'un compteur gaz G10/G16",
                    cost: '383,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "[Basse pression] Placement d'un compteur gaz G25",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 4,
                    type: "[Basse pression] Placement d'un compteur gaz G40",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 5,
                    type: "[Basse pression] Placement d'un compteur gaz G65",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 6,
                    type: "[Basse pression] Placement d'un compteur gaz G100",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 7,
                    type: "[Moyenne pression] Placement d'un boîtier pour mise à dispositon d'impulsions et raccordement au compteur gaz",
                    cost: '545,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 8,
                    type: "[Moyenne pression] Placement d'un câble pour mise à disposition d'impulsions au compteur gaz",
                    cost: '44,77',
                },
            ],
        },
    },
    {
        key: '(R)ouvrir une installation au gaz naturel/un compteur scellé(e)',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'isModal',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/nouveau-raccordement-gaz',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'In dienst stellen (analoge gasmeter)',
                    cost: '88,00',
                },
                {
                    provider: 'FLUVIUS',
                    id: 2,
                    type: 'In dienst stellen (digitale gasmeter)',
                    cost: '10,70',
                },
                {
                    provider: 'FLUVIUS',
                    id: 3,
                    type: 'In dienst stellen extra analoge gasmeter gelijktijdig met een eerste meter',
                    cost: '58,82',
                },
                {
                    provider: 'FLUVIUS',
                    id: 4,
                    type: 'In dienst stellen extra digitale gasmeter gelijktijdig met een eerste meter',
                    cost: '10,70',
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "[Basse pression] Placement d'un compteur gaz de type G4/G6",
                    cost: '147,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "[Basse pression] Placement d'un compteur gaz G10/G16",
                    cost: '383,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "[Basse pression] Placement d'un compteur gaz G25",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 4,
                    type: "[Basse pression] Placement d'un compteur gaz G40",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 5,
                    type: "[Basse pression] Placement d'un compteur gaz G65",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 6,
                    type: "[Basse pression] Placement d'un compteur gaz G100",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 7,
                    type: "Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h",
                    cost: '168',
                },
                {
                    provider: 'SIBELGA',
                    id: 8,
                    type: "Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h",
                    cost: '69',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: 'Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h',
                    cost: '168'
                },
                {
                    provider: 'ORES',
                    id: 2,
                    type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h',
                    cost: '69',
                },
            ],
        },
    },
    {
        key: 'Modifier la puissance',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'https://extranet.ores.be/fr/work-demands/existing-connection',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/modifier-puissance-compteur-electrique',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'Verzwaren gasmeter tot 10 m³n/h op bestaande aansluiting',
                    cost: '296,75',
                },
                {
                    provider: 'FLUVIUS',
                    id: 2,
                    type: 'Verzwaren gasmeter tot 10m³n/h naar gasmeter 16 m³n/h tot max 25 m³n/h op bestaande aansluiting',
                    cost: '1026,49',
                },
                {
                    provider: 'FLUVIUS',
                    id: 3,
                    type: 'Verzwaren gasmeter > 10 m³n/h tot max 25 m³n/h op bestaande aansluiting ',
                    cost: '1026,49',
                },
                {
                    provider: 'FLUVIUS',
                    id: 4,
                    type: 'Verzwaren gasmeter > 25 m³n/h tot max 40 m³n/h op bestaande aansluiting',
                    cost: '1275,61',
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "[Basse pression] Placement d'un compteur gaz de type G4/G6",
                    cost: '147,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "[Basse pression] Placement d'un compteur gaz G10/G16",
                    cost: '383,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "[Basse pression] Placement d'un compteur gaz G25",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 4,
                    type: "[Basse pression] Placement d'un compteur gaz G40",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 5,
                    type: "[Basse pression] Placement d'un compteur gaz G65",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 6,
                    type: "[Basse pression] Placement d'un compteur gaz G100",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 7,
                    type: "Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h",
                    cost: '168',
                },
                {
                    provider: 'SIBELGA',
                    id: 8,
                    type: "Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h",
                    cost: '69',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: 'Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h',
                    cost: 'SUR DEVIS'
                },
                {
                    provider: 'ORES',
                    id: 4,
                    type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h => Renforcement par changement de pression',
                    cost: '135'
                },
                {
                    provider: 'ORES',
                    id: 2,
                    type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h => Renforcement ou déforcement de compteur sur conduite existante ou déplacement de compteur',
                    column: {
                        titles: [
                            'BP 21/25/98 mbar',
                            'MP 4,9 bar',
                            'Coffret',
                        ],
                        contents: [
                            {
                                id: 1,
                                BP212598mbar: '262',
                                MP49bar: '262',
                                box: '285',
                            },
                            {
                                id: 2,
                                BP212598mbar: '324',
                                MP49bar: '324',
                                box: '742',
                            },
                            {
                                id: 3,
                                BP212598mbar: '324',
                                MP49bar: '324',
                                box: '742',
                            },
                            {
                                id: 4,
                                BP212598mbar: '1.464',
                                MP49bar: '1.464',
                                box: '746',
                            },
                            {
                                id: 5,
                                BP212598mbar: '3.404',
                                MP49bar: '3.758',
                                box: '1.815',
                            },
                            {
                                id: 6,
                                BP212598mbar: '5.017',
                                MP49bar: '5.538',
                                box: '2.560',
                            },
                            {
                                id: 7,
                                BP212598mbar: '6.993',
                                MP49bar: '6.993',
                                box: '2.560',
                            },
                        ],
                    },
                },
                // {
                //     provider: 'ORES',
                //     id: 3,
                //     type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h => Renforcement par changement de pression',
                //     cost: '135',
                // },
            ],
        },
    },
    {
        key: 'Déplacer le compteur',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'https://extranet.ores.be/fr/work-demands/existing-connection',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/deplacement-compteur-gaz',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'Verplaatsen gasmeter <=10 m³n/h',
                    cost: '355,87',
                },
                {
                    provider: 'FLUVIUS',
                    id: 2,
                    type: 'Verplaatsen 2 gasmeters <=10 m³n/h op zelfde aansluiting Verplaatsen gasmeter > 10 m³n/h',
                    cost: '623,19',
                },
                {
                    provider: 'FLUVIUS',
                    id: 3,
                    type: 'Verplaatsen gasmeter > 10 m³n/h ',
                    cost: '355,87',
                },
                {
                    provider: 'FLUVIUS',
                    id: 4,
                    type: 'Verplaatsen bijkomende gasmeter <=10 m³n/h op zelfde aansluiting',
                    cost: '267,31',
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "[Basse pression] Placement d'un compteur gaz de type G4/G6",
                    cost: '147,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "[Basse pression] Placement d'un compteur gaz G10/G16",
                    cost: '383,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "[Basse pression] Placement d'un compteur gaz G25",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 4,
                    type: "[Basse pression] Placement d'un compteur gaz G40",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 5,
                    type: "[Basse pression] Placement d'un compteur gaz G65",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 6,
                    type: "[Basse pression] Placement d'un compteur gaz G100",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 7,
                    type: "Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h",
                    cost: '168',
                },
                {
                    provider: 'SIBELGA',
                    id: 8,
                    type: "Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h",
                    cost: '69',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: 'Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h',
                    cost: 'SUR DEVIS'
                },
                {
                    provider: 'ORES',
                    id: 4,
                    type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h => Renforcement par changement de pression',
                    cost: '135'
                },
                {
                    provider: 'ORES',
                    id: 2,
                    type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h => Renforcement ou déforcement de compteur sur conduite existante ou déplacement de compteur',
                    column: {
                        titles: [
                            'BP 21/25/98 mbar',
                            'MP 4,9 bar',
                            'Coffret',
                        ],
                        contents: [
                            {
                                id: 1,
                                BP212598mbar: '262',
                                MP49bar: '262',
                                box: '285',
                            },
                            {
                                id: 2,
                                BP212598mbar: '324',
                                MP49bar: '324',
                                box: '742',
                            },
                            {
                                id: 3,
                                BP212598mbar: '324',
                                MP49bar: '324',
                                box: '742',
                            },
                            {
                                id: 4,
                                BP212598mbar: '1.464',
                                MP49bar: '1.464',
                                box: '746',
                            },
                            {
                                id: 5,
                                BP212598mbar: '3.404',
                                MP49bar: '3.758',
                                box: '1.815',
                            },
                            {
                                id: 6,
                                BP212598mbar: '5.017',
                                MP49bar: '5.538',
                                box: '2.560',
                            },
                            {
                                id: 7,
                                BP212598mbar: '6.993',
                                MP49bar: '6.993',
                                box: '2.560',
                            },
                        ],
                    },
                },
            ],
        },
    },
    {
        key: 'Contrôler le compteur',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'showCallModal',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/controle-exactitude-compteur',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'ijking gasmeter op vraag van de klant incl. metervervanging(enkel te betalen indien meter goed is)',
                    cost: '1150,06',
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "Contrôle de l'exactitude d'un compteur gaz en laboratoire avec remplacement du compteur gaz",
                    cost: '444,07',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: "Contrôle métrologique d'un compteur gaz ≥ G160 en laboratoire",
                    cost: 'SUR DEVIS'
                },
                {
                    provider: 'ORES',
                    id: 2,
                    type: "Contrôle métrologique d'un compteur gaz G4-G6 en laboratoire",
                    cost: '488'
                },
                {
                    provider: 'ORES',
                    id: 3,
                    type: "Contrôle métrologique d'un compteur gaz G10-G16-G25 en laboratoire",
                    cost: '892'
                },
                {
                    provider: 'ORES',
                    id: 4,
                    type: "Contrôle métrologique d'un compteur gaz G40-G65 en laboratoire",
                    cost: '1264'
                },
                {
                    provider: 'ORES',
                    id: 5,
                    type: "Contrôle métrologique d'un compteur gaz > G65 en laboratoire",
                    cost: 'SUR DEVIS'
                },
            ],
        },
    },
    {
        key: 'Fermer le compteur',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'isModal',
            SIBELGA:
                'https://www.sibelga.be/fr/raccordements-et-compteurs/nouveau-raccordement-gaz',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'In dienst stellen (analoge gasmeter)',
                    cost: '88,00',
                },
                {
                    provider: 'FLUVIUS',
                    id: 2,
                    type: 'In dienst stellen (digitale gasmeter)',
                    cost: '10,70',
                },
                {
                    provider: 'FLUVIUS',
                    id: 3,
                    type: 'In dienst stellen extra analoge gasmeter gelijktijdig met een eerste meter',
                    cost: '58,82',
                },
                {
                    provider: 'FLUVIUS',
                    id: 4,
                    type: 'In dienst stellen extra digitale gasmeter gelijktijdig met een eerste meter',
                    cost: '10,70',
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "[Basse pression] Placement d'un compteur gaz de type G4/G6",
                    cost: '147,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "[Basse pression] Placement d'un compteur gaz G10/G16",
                    cost: '383,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "[Basse pression] Placement d'un compteur gaz G25",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 4,
                    type: "[Basse pression] Placement d'un compteur gaz G40",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 5,
                    type: "[Basse pression] Placement d'un compteur gaz G65",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 6,
                    type: "[Basse pression] Placement d'un compteur gaz G100",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 7,
                    type: "Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h",
                    cost: '168',
                },
                {
                    provider: 'SIBELGA',
                    id: 8,
                    type: "Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h",
                    cost: '69',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: 'Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h',
                    cost: '168'
                },
                {
                    provider: 'ORES',
                    id: 2,
                    type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h',
                    cost: '69',
                },
            ],
        },
    },
    {
        key: 'Enlever le compteur',
        linkRedirection: {
            FLUVIUS:
                'https://mijnpostcode.fluvius.be/?lang=nl&applicatie=Aansluiting-aanvragen',
            ORES: 'https://extranet.ores.be/fr/work-demands/existing-connection',
            SIBELGA:
                'https://my.sibelga.be/?language=fr&_ga=2.38475179.945166564.1639909831-2070307214.1639336899#/fr/',
        },
        provider: {
            FLUVIUS: [
                {
                    provider: 'FLUVIUS',
                    id: 1,
                    type: 'Sloop 1 gasmeter van bestaande aansluiting, aansluiting blijft behouden',
                    cost: '125,89',
                },
                {
                    provider: 'FLUVIUS',
                    id: 2,
                    type: 'Sloop 1 extra gasmeter van bestaande aansluiting, aansluiting blijft behouden',
                    cost: '46,75',
                },
            ],
            SIBELGA: [
                {
                    provider: 'SIBELGA',
                    id: 1,
                    type: "[Basse pression] Placement d'un compteur gaz de type G4/G6",
                    cost: '147,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 2,
                    type: "[Basse pression] Placement d'un compteur gaz G10/G16",
                    cost: '383,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 3,
                    type: "[Basse pression] Placement d'un compteur gaz G25",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 4,
                    type: "[Basse pression] Placement d'un compteur gaz G40",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 5,
                    type: "[Basse pression] Placement d'un compteur gaz G65",
                    cost: '1686,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 6,
                    type: "[Basse pression] Placement d'un compteur gaz G100",
                    cost: '447,00',
                },
                {
                    provider: 'SIBELGA',
                    id: 7,
                    type: "Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h",
                    cost: '168',
                },
                {
                    provider: 'SIBELGA',
                    id: 8,
                    type: "Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h",
                    cost: '69',
                },
            ],
            ORES: [
                {
                    provider: 'ORES',
                    id: 1,
                    type: 'Réseau de distribution alimenté par une cabine sur réseau gaz naturel MP avec un débit supérieur à 160 m³/h',
                    cost: 'SUR DEVIS'
                },
                {
                    provider: 'ORES',
                    id: 4,
                    type: 'Réseau de distribution basse pression (BP) ou réseau de distribution moyenne pression (MP ≤5 bar) avec un débit maximum de 160 m³/h => Enlèvement compteur gaz (déconnexion du branchement non comprise)',
                    cost: '196'
                },
            ],
        },
    },
    {
        key: 'Signalez une odeur de gaz',
        FLUVIUS: 'Appelez immédiatement le 0800 650 65',
        SIBELGA: 'Appelez immédiatement le 0800 19 400',
        ORES: 'Appelez immédiatement le 0800 87 087',
    },
    {
        key: 'Je n’ai plus de gaz: que faire?',
        options: [
            'Votre compteur de gaz se trouve à l’extérieur (coffret) ou dans un local commun (appartements)',
            'Vous avez plusieurs appareils au gaz naturel'
        ],
    },
    {
        key: 'Interruption de courant',
        content: 'Une alerte vous sera envoyée en cas d’interruption programmée de courant',
        link: 'https://www.fluvius.be/nl/meer-weten/stroomonderbrekingen'
    }
];
